-- ============================================================================
-- Employee shift change audit (production + HR)
-- ============================================================================
-- Run this migration against your database before using /production/shift-change
-- or relying on shift-change history.
--
-- 1) Log table: one row per change to hr_emp.shift_code
-- 2) Trigger: any UPDATE that changes shift_code inserts a row (HR UI, bulk
--    CSV via updateEmployee, production shift-change page, or ad-hoc SQL)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.prdn_emp_shift_change_log (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  emp_id character varying NOT NULL,
  shift_code_from character varying NOT NULL,
  shift_code_to character varying NOT NULL,
  changed_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  changed_by character varying NOT NULL,
  CONSTRAINT prdn_emp_shift_change_log_pkey PRIMARY KEY (id),
  CONSTRAINT prdn_emp_shift_change_log_emp_id_fkey
    FOREIGN KEY (emp_id) REFERENCES public.hr_emp (emp_id),
  CONSTRAINT prdn_emp_shift_change_log_shift_from_fkey
    FOREIGN KEY (shift_code_from) REFERENCES public.hr_shift_master (shift_code),
  CONSTRAINT prdn_emp_shift_change_log_shift_to_fkey
    FOREIGN KEY (shift_code_to) REFERENCES public.hr_shift_master (shift_code)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_prdn_emp_shift_change_log_emp_changed
  ON public.prdn_emp_shift_change_log (emp_id, changed_at DESC);

COMMENT ON TABLE public.prdn_emp_shift_change_log IS
  'Audit trail for hr_emp.shift_code changes (HR, bulk update, production shift-change).';

-- ---------------------------------------------------------------------------
-- Trigger: log when shift_code actually changes
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.hr_emp_shift_change_log_fn()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'UPDATE' AND NEW.shift_code IS DISTINCT FROM OLD.shift_code THEN
    INSERT INTO public.prdn_emp_shift_change_log (
      emp_id,
      shift_code_from,
      shift_code_to,
      changed_at,
      changed_by
    ) VALUES (
      NEW.emp_id,
      OLD.shift_code,
      NEW.shift_code,
      COALESCE(NEW.modified_dt, CURRENT_TIMESTAMP),
      NEW.modified_by
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS hr_emp_shift_change_log_trg ON public.hr_emp;

CREATE TRIGGER hr_emp_shift_change_log_trg
  AFTER UPDATE OF shift_code ON public.hr_emp
  FOR EACH ROW
  WHEN (OLD.shift_code IS DISTINCT FROM NEW.shift_code)
  EXECUTE PROCEDURE public.hr_emp_shift_change_log_fn();

-- ---------------------------------------------------------------------------
-- Optional: menu row for authorised users (adjust IDs/order/parent to match your menu table)
-- ---------------------------------------------------------------------------
-- Example only — uncomment and edit after inspecting your `menu` table:
-- INSERT INTO menu (menu_id, menu_name, menu_path, parent_menu_id, menu_order, is_visible, is_enabled)
-- VALUES (gen_random_uuid(), 'Shift change', '/production/shift-change', '<production_parent_uuid>', 50, true, true);
