-- Fix for std_vehicle_work_flow table to use derived_sw_code instead of swtd_id
-- This maintains consistency with other tables

ALTER TABLE public.std_vehicle_work_flow 
DROP CONSTRAINT IF EXISTS std_vehicle_work_flow_swtd_id_fkey,
DROP CONSTRAINT IF EXISTS std_vehicle_work_flow_dependency_fkey;

ALTER TABLE public.std_vehicle_work_flow 
DROP COLUMN IF EXISTS swtd_id,
DROP COLUMN IF EXISTS dependency_swtd_id;

ALTER TABLE public.std_vehicle_work_flow 
ADD COLUMN derived_sw_code character varying(15) NOT NULL,
ADD COLUMN dependency_derived_sw_code character varying(15);

ALTER TABLE public.std_vehicle_work_flow 
ADD CONSTRAINT std_vehicle_work_flow_derived_sw_code_fkey 
  FOREIGN KEY (derived_sw_code) REFERENCES public.std_work_type_details(derived_sw_code) ON DELETE RESTRICT,
ADD CONSTRAINT std_vehicle_work_flow_dependency_fkey 
  FOREIGN KEY (dependency_derived_sw_code) REFERENCES public.std_work_type_details(derived_sw_code) ON DELETE SET NULL,
ADD CONSTRAINT std_vehicle_work_flow_unique UNIQUE (wo_type_id, derived_sw_code, sequence_order);

-- Fix timestamp consistency - make all tables use timestamp without time zone
ALTER TABLE public.std_vehicle_work_flow 
ALTER COLUMN created_dt TYPE timestamp without time zone,
ALTER COLUMN modified_dt TYPE timestamp without time zone;

-- Add indexes for better performance
CREATE INDEX IF NOT EXISTS idx_std_work_type_details_sw_code ON public.std_work_type_details(sw_code);
CREATE INDEX IF NOT EXISTS idx_std_work_skill_mapping_derived_sw_code ON public.std_work_skill_mapping(derived_sw_code);
CREATE INDEX IF NOT EXISTS idx_std_work_skill_mapping_sc_name ON public.std_work_skill_mapping(sc_name);
CREATE INDEX IF NOT EXISTS idx_std_skill_time_standards_wsm_id ON public.std_skill_time_standards(wsm_id);
CREATE INDEX IF NOT EXISTS idx_std_vehicle_work_flow_wo_type_id ON public.std_vehicle_work_flow(wo_type_id);
CREATE INDEX IF NOT EXISTS idx_std_vehicle_work_flow_derived_sw_code ON public.std_vehicle_work_flow(derived_sw_code);

-- Create missing plan_prod_times table for production planning
CREATE TABLE IF NOT EXISTS public.plan_prod_times (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  plan_id integer NOT NULL,
  slot_order integer NOT NULL,
  entry_time character varying(10) NOT NULL,
  created_dt timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT plan_prod_times_pkey PRIMARY KEY (id),
  CONSTRAINT plan_prod_times_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plan_prod_plan_per_day(id) ON DELETE CASCADE
);

-- Add indexes for plan_prod_times table
CREATE INDEX IF NOT EXISTS idx_plan_prod_times_plan_id ON public.plan_prod_times(plan_id);
CREATE INDEX IF NOT EXISTS idx_plan_prod_times_slot_order ON public.plan_prod_times(slot_order); 