-- Non-commercial work orders (Accounts > Create work order)
-- Separate from prdn_wo_details.

CREATE TABLE public.acct_non_commercial_wo (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  wo_no character varying(64) NOT NULL,
  prdn_wo_no character varying(30) NULL,
  customer_name character varying(255) NOT NULL,
  wo_date date NOT NULL,
  nc_category character varying(20) NOT NULL,
  wo_type character varying(100) NULL,
  wo_model character varying(20) NULL,
  comments text NULL,
  created_by character varying(255) NULL,
  created_dt timestamp with time zone NOT NULL DEFAULT now(),
  modified_by character varying(255) NULL,
  modified_dt timestamp with time zone NULL,
  CONSTRAINT acct_non_commercial_wo_pkey PRIMARY KEY (id),
  CONSTRAINT acct_non_commercial_wo_wo_no_key UNIQUE (wo_no),
  CONSTRAINT acct_non_commercial_wo_comments_when_needed CHECK (
    (
      coalesce(trim(wo_model), '') <> ''
      AND coalesce(trim(wo_type), '') <> ''
    )
    OR (comments IS NOT NULL AND length(trim(comments)) > 0)
  )
);

CREATE INDEX idx_acct_non_commercial_wo_wo_date ON public.acct_non_commercial_wo (wo_date DESC);
CREATE INDEX idx_acct_non_commercial_wo_nc_category ON public.acct_non_commercial_wo (nc_category);
CREATE INDEX idx_acct_non_commercial_wo_wo_type ON public.acct_non_commercial_wo (wo_type);
CREATE INDEX idx_acct_non_commercial_wo_prdn_wo_no ON public.acct_non_commercial_wo (prdn_wo_no)
  WHERE prdn_wo_no IS NOT NULL;

COMMENT ON TABLE public.acct_non_commercial_wo IS 'Non-commercial / internal work orders; separate from prdn_wo_details.';
COMMENT ON COLUMN public.acct_non_commercial_wo.wo_no IS 'Non-commercial WO number (e.g. JBC/… or OTH/… from nc_category + user input). No spaces.';
COMMENT ON COLUMN public.acct_non_commercial_wo.prdn_wo_no IS 'Optional link to commercial WO number; may be null or empty.';
COMMENT ON COLUMN public.acct_non_commercial_wo.nc_category IS 'From sys_data_elements de_name Non Commercial WO Type (de_value).';
COMMENT ON COLUMN public.acct_non_commercial_wo.wo_type IS 'From mstr_wo_type.wo_type_code; if blank with wo_model, comments required.';
COMMENT ON COLUMN public.acct_non_commercial_wo.wo_model IS 'From mstr_wo_type.wo_type_name; if blank with wo_type, comments required.';
